BrainStew/Controllers/DownlineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BrainStew.Models;
using BrainStew.Filter;
using BrainStew.Controllers;

namespace BrainStew.Controllers
{
    public class DownlineController : UserBaseController
    {
        //
        // GET: /Downline/

        public ActionResult DirectList(string Ids)
        {
            List<SelectListItem> AssociateStatus = Common.AssociateStatus();
            ViewBag.ddlStatus = AssociateStatus;
            List<SelectListItem> Leg = Common.LegType();
            ViewBag.ddlleg = Leg;

            Reports model = new Reports();
           
            List<Reports> lst = new List<Reports>();
            if (Ids == null || Ids == "")
            {
                model.Ids = Session["Pk_UserId"].ToString();
               
            }
            else
            {
                model.Ids = Ids;
              
            }
            model.DirectStatus = "Self";
            model.Fk_UserId = Session["Pk_UserId"].ToString();
           
            DataSet ds = model.GetDirectList();

            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                if(ds.Tables[0].Rows[0][0].ToString()!="0")
                {
                    Ids = "";
                    foreach (DataRow r in ds.Tables[0].Rows)
                    {
                        Reports obj = new Reports();
                        obj.Mobile = r["Mobile"].ToString();
                        obj.Email = r["Email"].ToString();
                        obj.SponsorId = r["SponsorId"].ToString();
                        obj.SponsorName = r["SponsorName"].ToString();
                        obj.JoiningDate = r["JoiningDate"].ToString();
                        obj.Leg = r["Leg"].ToString();
                        obj.PermanentDate = (r["PermanentDate"].ToString());
                        obj.Status = (r["Status"].ToString());
                        obj.LoginId = (r["LoginId"].ToString());
                        obj.Name = (r["Name"].ToString());
                        obj.Level = (r["Lvl"].ToString());
                        obj.Package = (r["ProductName"].ToString());
                        Ids = Ids + r["PK_UserId"].ToString() + ",";
                        lst.Add(obj);
                    }
                    model.lstassociate = lst;
                    model.Ids = Ids;
                }
                
            }
            return View(model);
        }

        [HttpPost]
        [ActionName("DirectList")]
        [OnAction(ButtonName = "Search")]
        public ActionResult DirectListBy(Reports model)
        {

            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");
            List<Reports> lst = new List<Reports>();

            if (model.Ids == null || model.Ids == "")
            {
                model.Ids = Session["Pk_UserId"].ToString();

            }
            model.Fk_UserId = Session["Pk_UserId"].ToString();

            DataSet ds = model.GetDirectList();

            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                string Ids = "";
                foreach (DataRow r in ds.Tables[0].Rows)
                {

                    Reports obj = new Reports();
                    obj.Mobile = r["Mobile"].ToString();
                    obj.Email = r["Email"].ToString();
                    obj.SponsorId = r["SponsorId"].ToString();
                    obj.SponsorName = r["SponsorName"].ToString();
                    obj.JoiningDate = r["JoiningDate"].ToString();
                    obj.Leg = r["Leg"].ToString();
                    obj.PermanentDate = (r["PermanentDate"].ToString());
                    obj.Status = (r["Status"].ToString());
                    obj.LoginId = (r["LoginId"].ToString());
                    obj.Name = (r["Name"].ToString());
                    obj.Level = (r["Lvl"].ToString());
                    obj.Package = (r["ProductName"].ToString());
                    Ids = Ids + r["PK_UserId"].ToString() + ",";
                    lst.Add(obj);
                }
                model.lstassociate = lst;
                model.Ids = Ids;
            }
            List<SelectListItem> AssociateStatus = Common.AssociateStatus();
            ViewBag.ddlStatus = AssociateStatus;
            List<SelectListItem> Leg = Common.LegType();
            ViewBag.ddlleg = Leg;
            return View(model);
        }


        public ActionResult DownLineList()
        {
            List<SelectListItem> AssociateStatus = Common.AssociateStatus();
            ViewBag.ddlStatus = AssociateStatus;
            List<SelectListItem> Leg = Common.LegType();
            ViewBag.ddlleg = Leg;

            Reports model = new Reports();
            List<Reports> lst = new List<Reports>();
            model.LoginId = Session["LoginId"].ToString();
            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");
            DataSet ds = model.GetDownlineList();

            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    Reports obj = new Reports();
                    obj.Name = r["Name"].ToString();
                    obj.LoginId = r["LoginId"].ToString();
                    obj.JoiningDate = r["JoiningDate"].ToString();
                    obj.Leg = r["Leg"].ToString();
                    obj.PermanentDate = (r["PermanentDate"].ToString());
                    obj.Status = (r["Status"].ToString());
                    obj.Mobile = (r["Mobile"].ToString());
                    obj.Package = (r["ProductName"].ToString());
                    lst.Add(obj);
                }
                model.lstassociate = lst;


            }
            return View(model);
        }
        [HttpPost]
        [ActionName("DownLineList")]
        [OnAction(ButtonName = "Search")]
        public ActionResult DownLineListBy(Reports model)
        {

            List<Reports> lst = new List<Reports>();
            model.LoginId = Session["LoginId"].ToString();
            DataSet ds = model.GetDownlineList();

            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    Reports obj = new Reports();
                    obj.Name = r["Name"].ToString();
                    obj.LoginId = r["LoginId"].ToString();
                    obj.JoiningDate = r["JoiningDate"].ToString();
                    obj.Leg = r["Leg"].ToString();
                    obj.PermanentDate = (r["PermanentDate"].ToString());
                    obj.Status = (r["Status"].ToString());
                    obj.Mobile = (r["Mobile"].ToString());
                    obj.Package = (r["ProductName"].ToString());
                    lst.Add(obj);
                }
                model.lstassociate = lst;
            }
            List<SelectListItem> AssociateStatus = Common.AssociateStatus();
            ViewBag.ddlStatus = AssociateStatus;
            List<SelectListItem> Leg = Common.LegType();
            ViewBag.ddlleg = Leg;
            return View(model);
        }
        #region  associate tree
        public ActionResult AssociateTree(AssociateBooking model, string AssociateID)
        {
            if (AssociateID != null && AssociateID != "")
            {
                model.Fk_UserId = AssociateID;
            }
            else
            {
                model.Fk_UserId = Session["Pk_UserId"].ToString();
            }
            model.FK_RootId = Session["Pk_UserId"].ToString();
            List<AssociateBooking> lst = new List<AssociateBooking>();
            DataSet ds = model.GetDownlineTree();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                ViewBag.Fk_SponsorId = ds.Tables[0].Rows[0]["Fk_SponsorId"].ToString();
                ViewBag.LoginId = ds.Tables[0].Rows[0]["LoginId"].ToString();
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    AssociateBooking obj = new AssociateBooking();
                    obj.Fk_UserId = r["Pk_UserId"].ToString();
                    obj.Fk_SponsorId = r["Fk_SponsorId"].ToString();
                    obj.LoginId = r["LoginId"].ToString();
                    obj.FirstName = r["FirstName"].ToString();
                    obj.Status = r["Status"].ToString();
                    obj.ActiveStatus = r["ActiveStatus"].ToString();
                    obj.SponsorID = r["SponsorId"].ToString();
                    obj.SponsorName = r["SponsorName"].ToString();
                    obj.ActivationDate = r["PermanentDate"].ToString();
                    obj.Mobile = r["Mobile"].ToString();
                    obj.Lvl = r["Level"].ToString();
                    lst.Add(obj);
                }
                model.lstPlot = lst;
            }
            return View(model);
        }
        #endregion
    }
}

BrainStew/Views/Downline/DirectList.cshtml
@model BrainStew.Models.Reports
@{
    ViewBag.Title = "DirectList";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
@using (Html.BeginForm("DirectList", "Downline", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{
    <div class="container">
        <div class="row layout-top-spacing">
            <div class="col-lg-12 col-12 layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>DownTeam Tree</h4>
                                <span class="text-danger">
                                    @TempData["pin"]
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content widget-content-area">
                        <div class="widget-content widget-content-area br-6">

                            <div class="row">
                                @*<div class="col-lg-3">
                                    <div class="form-group">
                                        <label>  Name </label>
                                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                                    </div>
                                </div>*@
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>From Date  </label>
                                        @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control",@readonly=true })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>To Date  </label>
                                        @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @readonly = true })
                                    </div>
                                </div>
                                @*<div class="col-md-3">
                                        <div class="form-group">
                                            <label>Leg</label>
                                            @Html.DropDownListFor(m => m.Leg, new SelectList(ViewBag.ddlleg, "Value", "Text"), new { @class = "form-control" })
                                        </div>
                                    </div>*@
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Status</label>
                                        @Html.DropDownListFor(m => m.Status, new SelectList(ViewBag.ddlStatus, "Value", "Text"), new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Self/Team</label>
                                        <input type="hidden" id="hdf" value="@Model.DirectStatus">
                                        <select id="DirectStatus" name="DirectStatus" class = "form-control">
                                            <option value="0">-select-</option>
                                            <option value="Self">Self</option>
                                            <option value="Team">Team</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-3" style="margin-top:15px;">
                                    <div class="form-group">
                                        <br />
                                        <input type="submit" id="btnSearch" class="btn btn-success pull-left" name="Search" value="Search" />
                                    </div>
                                </div>
                            </div>
                            <center>
                                <div>
                                    @if (Model != null)
                                    {
                                        if ( Model.lstassociate != null)
                                        {
                                            <a href="/Downline/DirectList?Ids=@Model.Ids" id="btnDown" class="btn btn-info btn-sm">Next</a>
                                        }
                                        else if (Model.lstassociate == null)
                                        {
                                            <a href="/Downline/DirectList" id="btnDown" class="btn btn-info btn-sm">Back</a>
                                        }
                                    }
                                </div>
                            </center>

                            <!-- /.panel-heading -->
                            <div class="table-responsive">
                                <table class="table table-hover non-hover" data-page-length='20' id="html5-extension">
                                    <thead>
                                        <tr>
                                            <th>Sr No.</th>
                                            <th>LoginId</th>
                                            <th>Name</th>
                                            <th>Sponsor Id</th>
                                            <th>Mobile</th>
                                            @*<th>Leg</th>*@
                                            @*<th>Joining Date</th>*@
                                            <th>Package</th>
                                            <th>Activation Date</th>
                                            <th>Level</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model != null)
                                        {
                                            if (Model.lstassociate != null)
                                            {
                                                int i = 1;
                                                foreach (var Item in Model.lstassociate)
                                                {
                                                    <tr class="text-left">
                                                        <td>@i</td>

                                                        <td>@Item.LoginId</td>
                                                        <td>@Item.Name</td>
                                                        <td>@Item.SponsorId</td>
                                                        <td>@Item.Mobile</td>
                                                        @*<td>@Item.Mobile</td>
                                                            <td>@Item.Email</td>*@
                                                        @*<td>@Item.Leg</td>*@
                                                        @*<td>@Item.JoiningDate</td>*@
                                                        <td>@Item.Package</td>
                                                        <td>@Item.PermanentDate</td>
                                                        <td>@Item.Level</td>
                                                        <td>@Item.Status</td>

                                                    </tr>
                                                    i++;
                                                }

                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css" />

<script>
    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
    });
    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
    });
</script>
<script>
    $(document).ready(function () {
        $("#DirectStatus").val($("#hdf").val()).attr("selected", "selected");
        $('#dataTables-example').DataTable({
            responsive: true
        });

    });
</script>

BrainStew/Views/Downline/DownLineList.cshtml
@model BrainStew.Models.Reports
@{
    ViewBag.Title = "DownLineList";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

@using (Html.BeginForm("DownLineList", "Downline", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{
    <div class="container">
        <div class="row layout-top-spacing">
            <div class="col-lg-12 col-12 layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>Direct List</h4>
                                <span class="text-danger">
                                    @TempData["pin"]
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content widget-content-area">
                        <div class="widget-content widget-content-area br-6">

                            <div class="row">
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>  Name </label>
                                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>From Date  </label>
                                        @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label>To Date  </label>
                                        @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                @*<div class="col-md-3">
                                    <div class="form-group">
                                        <label>Leg</label>
                                        @Html.DropDownListFor(m => m.Leg, new SelectList(ViewBag.ddlleg, "Value", "Text"), new { @class = "form-control" })
                                    </div>
                                </div>*@
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Status</label>
                                        @Html.DropDownListFor(m => m.Status, new SelectList(ViewBag.ddlStatus, "Value", "Text"), new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <br />
                                        <input type="submit" id="btnSearch" class="btn btn-success pull-left" name="Search" value="Search" />
                                    </div>
                                </div>
                            </div>
                            <!-- /.panel-heading -->
                            <div class="table-responsive">
                                <table class="table mb-0" id="example23">
                                    <thead>
                                        <tr>
                                            <th>Sr No.</th>

                                            <th>Login Id</th>
                                            <th>Name</th>
                                            <th>Leg</th>
                                            <th>Joining Date</th>
                                            <th>Package</th>
                                            <th>Activation Date</th>
                                            <th>Mobile No</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model != null)
                                        {
                                            if (Model.lstassociate != null)
                                            {
                                                int i = 1;
                                                foreach (var Item in Model.lstassociate)
                                                {
                                                    <tr class="text-left">
                                                        <td>@i</td>

                                                        <td>@Item.LoginId</td>
                                                        <td>@Item.Name</td>
                                                        <td>@Item.Leg</td>
                                                        <td>@Item.JoiningDate</td>
                                                        <td>@Item.Package</td>
                                                        <td>@Item.PermanentDate</td>
                                                        <td>@Item.Mobile</td>

                                                        <td>@Item.Status</td>

                                                    </tr>
                                                    i++;
                                                }

                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script src="../vendor/jquery/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
<script>

    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
    });
    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
    });
</script>
<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            responsive: true
        });

    });
</script>