BrainStew/Models/Permisssions.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace BrainStew.Models
{
    public class Permisssions
    {
        public string Fk_UserTypeId { get; set; }
        public string Fk_UserId { get; set; }
        public string Fk_FormTypeId { get; set; }
        public string Fk_FormId { get; set; }
        public string FormView { get; set; }
        public string FormSave { get; set; }
        public string FormUpdate { get; set; }
        public string FormDelete { get; set; }
        public string FormName { get; set; }
        public string LoginId { get; set; }
        public string ToLoginID { get; set; }
        public string EmployeeLoginId { get; set; }

        public bool IsSaveValue { get; set; }
        public bool IsUpdateValue { get; set; }
        public bool IsSelectValue { get; set; }
        public bool IsDeleteValue { get; set; }
        public string SelectedValue { get; set; }
        public string CreatedBy { get; set; }
        public DataTable UserTypeFormPermisssion { get; set; }
        public string EmployeeId { get; set; }

        public List<Permisssions> lstpermission = new List<Permisssions>();

        public DataSet GetFormPermission()
        {
            SqlParameter[] para = {
                                      new SqlParameter("@fk_userid", Fk_UserId),
                                      new SqlParameter("@Pk_FormTypeId", Fk_FormTypeId) };
            DataSet ds = DBHelper.ExecuteQuery("GetPemissionData", para);
            return ds;
        }
        public DataSet SavePermisssion()
        {
            SqlParameter[] para = {
                                      new SqlParameter("@UserTypeFormPermisssion", UserTypeFormPermisssion),
                                      new SqlParameter("@CreatedBy", CreatedBy),
                                      new SqlParameter("@Fk_UserId", Fk_UserId),
                                      new SqlParameter("@Fk_FormTypeId", Fk_FormTypeId)
                                  };
            DataSet ds = DBHelper.ExecuteQuery("SetFormPermission", para);
            return ds;
        }
   
    }
}

BrainStew/Controllers/PermisssionsController.cs
using BrainStew.Filter;
using BrainStew.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrainStew.Controllers
{
    public class PermisssionsController : Controller
    {
        // GET: Permisssions
        public ActionResult SetPermission(Permisssions model)
        {

            DataSet ds1 = new DataSet();

            #region ddlformtype
            Common obj = new Common();
            List<SelectListItem> ddlformtype = new List<SelectListItem>();
            ds1 = obj.BindFormTypeMaster();
            if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds1.Tables[0].Rows)
                { ddlformtype.Add(new SelectListItem { Text = r["FormType"].ToString(), Value = r["PK_FormTypeId"].ToString() }); }
            }

            ViewBag.ddlformtype = ddlformtype;

            #endregion
            #region ddluser

            List<SelectListItem> ddluser = new List<SelectListItem>();
            EmployeeRegistrations emp = new EmployeeRegistrations();
            ds1 = emp.GetEmployeeData();
            if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds1.Tables[0].Rows)
                { ddluser.Add(new SelectListItem { Text = r["Name"].ToString(), Value = r["PK_AdminId"].ToString() }); }
            }
            else
            {
                ddluser.Add(new SelectListItem { Text = "Select User", Value = "0" });
            }

            ViewBag.ddluser = ddluser;

            #endregion

            return View();
        }
        [HttpPost]
        [ActionName("SetPermission")]
        [OnAction(ButtonName = "GetDetails")]
        public ActionResult GetPermission(Permisssions obj)
        {
            Permisssions model = new Permisssions();
            List<Permisssions> lst = new List<Permisssions>();
            DataSet ds = obj.GetFormPermission();
            if (ds != null && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Permisssions ob = new Permisssions();
                    ob.FormName = dr["FormName"].ToString();
                    ob.IsSelectValue = Convert.ToBoolean(dr["FormView"].ToString());
                    if (ob.IsSelectValue == false)
                    {
                        ob.SelectedValue = "";
                    }
                    else
                    {
                        ob.SelectedValue = "checked";
                    }
                    ob.IsSaveValue = Convert.ToBoolean(dr["FormSave"].ToString());
                    ob.IsUpdateValue = Convert.ToBoolean(dr["FormUpdate"].ToString());
                    ob.IsDeleteValue = Convert.ToBoolean(dr["FormDelete"].ToString());
                    ob.Fk_FormId = dr["PK_FormId"].ToString();
                    ob.Fk_FormTypeId = dr["pk_formtypeid"].ToString();
                    ob.Fk_UserId = dr["Fk_UserId"].ToString();
                    lst.Add(ob);
                }
                model.lstpermission = lst;
            }
            DataSet ds1 = new DataSet();

            #region ddlformtype
            Common obj1 = new Common();
            List<SelectListItem> ddlformtype = new List<SelectListItem>();
            ds1 = obj1.BindFormTypeMaster();
            if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds1.Tables[0].Rows)
                { ddlformtype.Add(new SelectListItem { Text = r["FormType"].ToString(), Value = r["PK_FormTypeId"].ToString() }); }
            }

            ViewBag.ddlformtype = ddlformtype;

            #endregion
            #region ddluser

            List<SelectListItem> ddluser = new List<SelectListItem>();
            EmployeeRegistrations emp = new EmployeeRegistrations();
            ds1 = emp.GetEmployeeData();
            if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds1.Tables[0].Rows)
                { ddluser.Add(new SelectListItem { Text = r["Name"].ToString(), Value = r["PK_AdminId"].ToString() }); }
            }

            ViewBag.ddluser = ddluser;

            #endregion
            return View(model);
        }

        [HttpPost]
        [ActionName("SetPermission")]
        [OnAction(ButtonName = "Save")]
        public ActionResult SavePermission(Permisssions obj)
        {
            string hdrows = Request["hdRows"].ToString();
            string chkSave = "";
            string chkupdate = "";
            string chkdelete = "";
            string chkselect = "";
            string hdfformtypeid = "";
            string hdfformid = "";
            string hdfloginid = "";
            DataTable dtpermission = new DataTable();

            dtpermission.Columns.Add("Fk_FormTypeId");
            dtpermission.Columns.Add("Fk_FormId");
            dtpermission.Columns.Add("IsSave");
            dtpermission.Columns.Add("IsUpdate");
            dtpermission.Columns.Add("IsDelete");
            dtpermission.Columns.Add("IsSelect");
            for (int i = 1; i < int.Parse(hdrows); i++)
            {

                try
                {
                    chkselect = Request["chkSelect_ " + i].ToString();
                }
                catch { chkselect = "0"; }
                hdfformtypeid = Request["hdFormtypeId_ " + i].ToString();
                hdfformid = Request["hdFormId_ " + i].ToString();
                hdfloginid = Request["hdLoginid_ " + i].ToString();

                dtpermission.Rows.Add(hdfformtypeid, hdfformid, "0", "0", "0", chkselect == "on" ? "1" : "0");

            }

            obj.UserTypeFormPermisssion = dtpermission;
            obj.CreatedBy = Session["Pk_AdminId"].ToString();
            obj.Fk_UserId = hdfloginid;
            obj.Fk_FormTypeId = hdfformtypeid;
            DataSet ds = obj.SavePermisssion();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {

                if (ds.Tables[0].Rows[0]["Msg"].ToString() == "1")
                {
                    TempData["Permission"] = "Permission set successfully.";
                }
                else
                {
                    TempData["Permission"] = ds.Tables[0].Rows[0]["Remark"].ToString();
                }
            }

            return RedirectToAction("SetPermission");

        }
    }
}

BrainStew/Views/Permisssions/SetPermission.cshtml
@model BrainStew.Models.Permisssions

@{
    ViewBag.Title = "SetPermission";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("SetPermission", "Permisssions", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{
    <div class="container">
        <div class="row layout-top-spacing">
            <div class="col-lg-12 col-12 layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>Set Permission</h4>
                                <span class="text-danger">
                                    @TempData["Permission"]
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content widget-content-area">

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Select User <span style="color: red">*</span></label>
                                    <div class="col-sm-9">
                                        @Html.DropDownListFor(m => m.Fk_UserId, new SelectList(ViewBag.ddluser, "Value", "Text"), new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Select Main Menu <span style="color: red">*</span></label>
                                    <div class="col-sm-9">
                                        @Html.DropDownListFor(m => m.Fk_FormTypeId, new SelectList(ViewBag.ddlformtype, "Value", "Text"), new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label"></label>
                                    <div class="col-sm-9">
                                        <input type="submit" id="GetDetails" name="GetDetails" class="btn btn-primary" value="Get Details" />
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="widget-content widget-content-area">
                            <div class="widget-content widget-content-area br-6">
                                <table id="html5-extension" class="table table-hover non-hover" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>Sr No.</th>
                                            <th>Form</th>
                                            <th>Form View</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model != null)
                                        {
                                            if (Model.lstpermission != null)
                                            {
                                                int i = 1;
                                                foreach (var item in Model.lstpermission)
                                                {
                                                    <tr>
                                                        <td>@i</td>
                                                        <td>
                                                            @Html.DisplayFor(m => item.FormName)
                                                        </td>
                                                        <td>
                                                            <input type="hidden" name="hdFormtypeId_ @i" id="hdFormtypeId_ @i" value="@item.Fk_FormTypeId" />
                                                            <input type="hidden" name="hdFormId_ @i" id="hdFormId_ @i" value="@item.Fk_FormId" />
                                                            <input type="hidden" name="hdLoginid_ @i" id="hdLoginid_ @i" value="@item.Fk_UserId" />
                                                            <input type="checkbox" name="chkSelect_ @i" id="chkSelect_ @i" @item.SelectedValue />
                                                        </td>
                                                    </tr>
                                                    i++;
                                                }
                                                <input type="hidden" id="hdRows" name="hdRows" value="@i" />
                                            }
                                        }
                                    </tbody>
                                </table>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <input type="submit" id="Save" name="Save" class="btn btn-success" value="Update" />
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}