BrainStew/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BrainStew.Models;
using System.Data.SqlClient;
using BrainStew.Controllers;
using System.Data;
using BrainStew.Filter;

namespace BrainStew.Controllers
{
    public class ReportController : UserBaseController
    {
        // GET: Report
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PayoutWalletLedger()
        {
            List<UserReports> lst = new List<UserReports>();
            UserReports model = new UserReports();
            model.LoginId = Session["LoginId"].ToString();
           
            DataSet ds = model.PayoutWalletLedger();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    UserReports obj = new UserReports();
                    obj.PK_PayoutWalletId = r["PK_PayoutWalletId"].ToString();
                    obj.FK_UserId = r["FK_UserId"].ToString();
                    obj.CrAmount = r["CrAmount"].ToString();
                    obj.DrAmount = r["DrAmount"].ToString();
                    obj.Narration = r["Narration"].ToString();
                    obj.TransactionDate = r["TransactionDate"].ToString();
                    obj.LoginId = r["LoginId"].ToString();
                    lst.Add(obj);
                }
                model.lst = lst;
            }
            User obj1 = new User();
            obj1.Fk_UserId = Session["Pk_userId"].ToString();
            DataSet ds11 = obj1.GetPayoutBalance();
            if (ds11 != null && ds11.Tables.Count > 0 && ds11.Tables[0].Rows.Count > 0)
            {
                ViewBag.BalanceAmount = ds11.Tables[0].Rows[0]["Balance"].ToString();
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult PayoutWalletLedger(UserReports model)
        {
            List<UserReports> lst = new List<UserReports>();
            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");
            model.LoginId = Session["LoginId"].ToString();
            DataSet ds = model.PayoutWalletLedger();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    UserReports obj = new UserReports();
                    obj.PK_PayoutWalletId = r["PK_PayoutWalletId"].ToString();
                    obj.FK_UserId = r["FK_UserId"].ToString();
                    obj.CrAmount = r["CrAmount"].ToString();
                    obj.DrAmount = r["DrAmount"].ToString();
                    obj.Narration = r["Narration"].ToString();
                    obj.TransactionDate = r["TransactionDate"].ToString();
                    obj.LoginId = r["LoginId"].ToString();
                    lst.Add(obj);
                }
                model.lst = lst;
            }
            return View(model);
        }
        public ActionResult BrainMatrixDonationList()
        {
            List<UserReports> lst = new List<UserReports>();
            UserReports model = new UserReports();
            model.LoginId = Session["LoginId"].ToString();
            DataSet ds = model.GetBrainMatrixDonation();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    UserReports obj = new UserReports();
                    obj.FromName = r["Name"].ToString();
                    obj.FromLoginId = r["LoginId"].ToString();
                    obj.Amount = r["Amount"].ToString();
                    obj.Level = r["BrainMatrixLevel"].ToString();
                    obj.TransactionDate = r["TransactionDate"].ToString();
                    lst.Add(obj);
                }
                model.lst = lst;
            }
            return View(model);
        }

        [HttpPost]
        [ActionName("BrainMatrixDonationList")]
        [OnAction(ButtonName = "btnSearch")]
        public ActionResult GetBrainMatrixDonationReport(UserReports model)
        {
            List<UserReports> lst = new List<UserReports>();
            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");
            model.LoginId = Session["LoginId"].ToString();
            DataSet ds = model.GetBrainMatrixDonation();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    UserReports obj = new UserReports();
                    obj.FromName = r["Name"].ToString();
                    obj.FromLoginId = r["LoginId"].ToString();
                    obj.Amount = r["Amount"].ToString();
                    obj.Level = r["BrainMatrixLevel"].ToString();
                    obj.TransactionDate = r["TransactionDate"].ToString();
                    lst.Add(obj);
                }
                model.lst = lst;
            }
            return View(model);
        }
        public ActionResult LevelIncomeTr1()
        {
            List<UserReports> lst = new List<UserReports>();
            UserReports model = new UserReports();
            model.LoginId = Session["LoginId"].ToString();
            DataSet ds = model.LevelIncomeTr1();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    UserReports obj = new UserReports();
                    obj.FromName = r["FromName"].ToString();
                    obj.FromLoginId = r["LoginId"].ToString();
                    obj.BusinessAmount = r["BusinessAmount"].ToString();
                    obj.Percentage = r["CommissionPercentage"].ToString();
                    obj.PayoutNo = r["PayoutNo"].ToString();
                    obj.Status = r["Status"].ToString();
                    obj.Amount = r["Amount"].ToString();
                    obj.Level = r["Lvl"].ToString();
                    obj.TransactionDate = r["TransactionDate"].ToString();
                    lst.Add(obj);
                }
                model.lst = lst;
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult LevelIncomeTr1(UserReports model)
        {
            List<UserReports> lst = new List<UserReports>();
            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");
            model.LoginId = Session["LoginId"].ToString();
            DataSet ds = model.LevelIncomeTr1();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    UserReports obj = new UserReports();
                    obj.FromName = r["FromName"].ToString();
                    obj.FromLoginId = r["LoginId"].ToString();
                    obj.BusinessAmount = r["BusinessAmount"].ToString();
                    obj.Percentage = r["CommissionPercentage"].ToString();
                    obj.PayoutNo = r["PayoutNo"].ToString();
                    obj.Status = r["Status"].ToString();
                    obj.Amount = r["Amount"].ToString();
                    obj.Level = r["Lvl"].ToString();
                    obj.TransactionDate = r["TransactionDate"].ToString();
                    lst.Add(obj);
                }
                model.lst = lst;
            }
            return View(model);
        }
        public ActionResult LevelIncomeTr2()
        {
            List<UserReports> lst = new List<UserReports>();
            UserReports model = new UserReports();
            model.LoginId = Session["LoginId"].ToString();
            DataSet ds = model.LevelIncomeTr2();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    UserReports obj = new UserReports();
                    obj.FromName = r["FromName"].ToString();
                    obj.FromLoginId = r["LoginId"].ToString();
                    obj.BusinessAmount = r["BusinessAmount"].ToString();
                    obj.Percentage = r["CommissionPercentage"].ToString();
                    obj.PayoutNo = r["PayoutNo"].ToString();
                    obj.Status = r["Status"].ToString();
                    obj.Amount = r["Amount"].ToString();
                    obj.Level = r["Lvl"].ToString();
                    obj.TransactionDate = r["TransactionDate"].ToString();
                    lst.Add(obj);
                }
                model.lst = lst;
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult LevelIncomeTr2(UserReports model)
        {
            List<UserReports> lst = new List<UserReports>();
            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");
            model.LoginId = Session["LoginId"].ToString();
            DataSet ds = model.LevelIncomeTr2();

BrainStew/Views/Report/BrainLevelBenefits.cshtml
@model BrainStew.Models.UserReports

@{
    ViewBag.Title = "BrainLevelBenefits";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<link href="~/plugins/flatpickr/flatpickr.css" rel="stylesheet" type="text/css">
<link href="~/plugins/flatpickr/custom-flatpickr.css" rel="stylesheet" type="text/css">
@using (Html.BeginForm("BrainLevelBenefits", "Report", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{
    <div class="container">
        <div class="row layout-top-spacing">
            <div class="col-lg-12 col-12 layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>BRAIN LEVEL BENEFITS</h4>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content widget-content-area">
                        <div class="row">
                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    <label>
                                        From Date
                                    </label>
                                    @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @Placeholder = "From Date" })

                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    <label> To Date</label>
                                    @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @Placeholder = "To Date" })

                                </div>
                            </div>

                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    <label>Status</label>
                                    <input type="hidden" value="@Model.Status" id="st" />
                                    <select id="Status" name="Status" class="form-control">
                                        <option value="">Select</option>
                                        <option value="0">Unpaid</option>
                                        <option value="1">Paid</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3" style="margin-top:28px">
                                <div class="form-group">
                                    <input type="submit" class="btn btn-success" value="Search" name="btnSearch" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <table id="html5-extension" class="table table-hover non-hover" data-page-length='20'>
                                <thead>
                                    <tr>
                                        <th>Sr No.</th>
                                        @*<th>Payout No</th>*@
                                        <th>From Member</th>
                                        <th>Donation Amount</th>
                                        @*<th>Percentage</th>*@
                                        <th>Benefits</th>
                                        @*<th>Level</th>*@
                                        <th>Status</th>
                                        <th>Transaction Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lst != null)
                                        {
                                            int i = 1;
                                            foreach (var Item in Model.lst)
                                            {
                                                <tr class="text-left">
                                                    <td>@i</td>
                                                    @*<td>@Item.PayoutNo</td>*@
                                                    <td>@Item.FromName (@Item.FromLoginId)</td>
                                                    <td>@Item.BusinessAmount</td>
                                                    @*<td>@Item.Percentage %</td>*@
                                                    <td>@Item.Amount</td>
                                                    @*<td>@Item.Level</td>*@
                                                    <td>@Item.Status</td>
                                                    <td>@Item.TransactionDate</td>
                                                </tr>
                                                i++;
                                            }
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/plugins/flatpickr/flatpickr.js"></script>
<script src="~/plugins/flatpickr/custom-flatpickr.js"></script>
<script src="~/BrainStewWebsite/assets/js/jquery.min.js"></script>
<script>
    var f3 = flatpickr(document.getElementById('FromDate'), {
        mode: "range"
    });
    var f4 = flatpickr(document.getElementById('ToDate'), {
        mode: "range"
    });
    //$("#Status").val($("#st").val()).attr("selected", "selected");
</script>

BrainStew/Views/Report/BrainMatrixBenefits.cshtml
@model BrainStew.Models.UserReports

@{
    ViewBag.Title = "BrainMatrixBenefits";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<link href="~/plugins/flatpickr/flatpickr.css" rel="stylesheet" type="text/css">
<link href="~/plugins/flatpickr/custom-flatpickr.css" rel="stylesheet" type="text/css">
@using (Html.BeginForm("BrainMatrixBenefits", "Report", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{
    <div class="container">
        <div class="row layout-top-spacing">
            <div class="col-lg-12 col-12 layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>BRAIN MATRIX BENEFITS</h4>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content widget-content-area">
                        @*<div class="row">
                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    <label>
                                        From Date
                                    </label>
                                    @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @Placeholder = "From Date" })

                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    <label> To Date</label>
                                    @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @Placeholder = "To Date" })

                                </div>
                            </div>

                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    <label>Status</label>
                                    <input type="hidden" value="@Model.Status" id="st" />
                                    <select id="Status" name="Status" class="form-control">
                                        <option value="">Select</option>
                                        <option value="0">Unpaid</option>
                                        <option value="1">Paid</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3" style="margin-top:28px">
                                <div class="form-group">
                                    <input type="submit" class="btn btn-success" value="Search" name="btnSearch" />
                                </div>
                            </div>
                        </div>*@
                        <div class="row">
                            <table id="html5-extension" class="table table-hover non-hover" data-page-length='20'>
                                <thead>
                                    <tr>
                                        <th>Sr No.</th>
                                        @*<th>Payout No</th>*@
                                        @*<th>From Member</th>
                                        <th>Donation Amount</th>*@
                                        @*<th>Percentage</th>*@
                                        <th>Level</th>
                                        <th>Benefits</th>
                                        @*<th>Level</th>*@
                                        @*<th>Status</th>
                                        <th>Transaction Date</th>*@
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lst != null)
                                        {
                                            int i = 1;
                                            foreach (var Item in Model.lst)
                                            {
                                                <tr class="text-left">
                                                    <td>@i</td>
                                                    @*<td>@Item.PayoutNo</td>*@
                                                    @*<td>@Item.FromName (@Item.FromLoginId)</td>
                                                    <td>@Item.BusinessAmount</td>*@
                                                    @*<td>@Item.Percentage %</td>*@
                                                    <td>@Item.Level</td>
                                                    <td>@Item.Amount</td>
                                                    @*<td>@Item.Level</td>*@
                                                    @*<td>@Item.Status</td>
                                                    <td>@Item.TransactionDate</td>*@
                                                </tr>
                                                i++;
                                            }
                                        }
                                    }
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th></th>
                                        <th>Total</th>
                                        <th>@ViewBag.Total</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/plugins/flatpickr/flatpickr.js"></script>
<script src="~/plugins/flatpickr/custom-flatpickr.js"></script>
<script src="~/BrainStewWebsite/assets/js/jquery.min.js"></script>
<script>
    var f3 = flatpickr(document.getElementById('FromDate'), {
        mode: "range"
    });
    var f4 = flatpickr(document.getElementById('ToDate'), {
        mode: "range"
    });
    //$("#Status").val($("#st").val()).attr("selected", "selected");
</script>

BrainStew/Views/Report/BrainMatrixDonationList.cshtml
@model BrainStew.Models.UserReports

@{
    ViewBag.Title = "BrainMatrixDonationList";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<link href="~/plugins/flatpickr/flatpickr.css" rel="stylesheet" type="text/css">
<link href="~/plugins/flatpickr/custom-flatpickr.css" rel="stylesheet" type="text/css">
@using (Html.BeginForm("BrainMatrixDonationList", "Report", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{
    <div class="container">
        <div class="row layout-top-spacing">
            <div class="col-lg-12 col-12 layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>Brain Matrix Donation List</h4>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content widget-content-area">
                        <div class="row">
                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    <label>
                                        From Date
                                    </label>
                                    @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @Placeholder = "From Date" })

                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    <label> To Date</label>
                                    @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @Placeholder = "To Date" })

                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3" style="margin-top:28px">
                                <div class="form-group">
                                    <input type="submit" class="btn btn-success" value="Search" name="btnSearch" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <table id="html5-extension" class="table table-hover non-hover" data-page-length='20'>
                                <thead>
                                    <tr>
                                        <th>Sr No.</th>
                                        <th>Name</th>
                                        <th>Amount</th>
                                        @*<th>Level</th>*@
                                        <th>Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lst != null)
                                        {
                                            int i = 1;
                                            foreach (var Item in Model.lst)
                                            {
                                                <tr class="text-left">
                                                    <td>@i</td>
                                                    <td>@Item.FromName (@Item.FromLoginId)</td>
                                                    <td>@Item.Amount</td>
                                                    <td>@Item.TransactionDate</td>
                                                </tr>

                                                i++;
                                            }
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/plugins/flatpickr/flatpickr.js"></script>
<script src="~/plugins/flatpickr/custom-flatpickr.js"></script>
<script src="~/BrainStewWebsite/assets/js/jquery.min.js"></script>
<script>
    var f3 = flatpickr(document.getElementById('FromDate'), {
        mode: "range"
    });
    var f4 = flatpickr(document.getElementById('ToDate'), {
        mode: "range"
    });
    //$("#Status").val($("#st").val()).attr("selected", "selected");
</script>

BrainStew/Views/Report/StewMatrixDonationList.cshtml
@model BrainStew.Models.UserReports

@{
    ViewBag.Title = "StewMatrixDonationList";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<link href="~/plugins/flatpickr/flatpickr.css" rel="stylesheet" type="text/css">
<link href="~/plugins/flatpickr/custom-flatpickr.css" rel="stylesheet" type="text/css">
@using (Html.BeginForm("StewMatrixDonationList", "Report", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{
    <div class="container">
        <div class="row layout-top-spacing">
            <div class="col-lg-12 col-12 layout-spacing">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>Stew Matrix Donation List</h4>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content widget-content-area">
                        <div class="row">
                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    <label>
                                        From Date
                                    </label>
                                    @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @Placeholder = "From Date" })

                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    <label> To Date</label>
                                    @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @Placeholder = "To Date" })

                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3" style="margin-top:28px">
                                <div class="form-group">
                                    <input type="submit" class="btn btn-success" value="Search" name="btnSearch" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <table id="html5-extension" class="table table-hover non-hover" data-page-length='20'>
                                <thead>
                                    <tr>
                                        <th>Sr No.</th>
                                        <th>Name</th>
                                        <th>Amount</th>
                                        @*<th>Level</th>*@
                                        <th>Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lst != null)
                                        {
                                            int i = 1;
                                            foreach (var Item in Model.lst)
                                            {
                                                <tr class="text-left">
                                                    <td>@i</td>
                                                    <td>@Item.FromName (@Item.FromLoginId)</td>
                                                    <td>@Item.Amount</td>
                                                    <td>@Item.TransactionDate</td>
                                                </tr>

                                                i++;
                                            }
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/plugins/flatpickr/flatpickr.js"></script>
<script src="~/plugins/flatpickr/custom-flatpickr.js"></script>
<script src="~/StewStewWebsite/assets/js/jquery.min.js"></script>
<script>
    var f3 = flatpickr(document.getElementById('FromDate'), {
        mode: "range"
    });
    var f4 = flatpickr(document.getElementById('ToDate'), {
        mode: "range"
    });
    //$("#Status").val($("#st").val()).attr("selected", "selected");
</script>